CREATE TABLE IF NOT EXISTS 'USERS' (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD CHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS 'PERSONALITIES' (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
FNAME VARCHAR(20) NOT NULL, 
MAIDENNAME VARCHAR(20),
MNAME VARCHAR(20), 
LNAME VARCHAR(20) NOT NULL,
BIRTHDAY DATE,
GENDER CHAR(10),
DESCRIPTION TEXT
);